### ISSUE TITLE
Failed to resolve: com.umeng.umsdk:common:2.0.0

### ISSUE THREAD

**Issue by whiteboolean** [codyer/component#1]
环境都是最新版，按照集成步骤下来，提示报错
友盟sdk导不进来:
Failed to resolve: com.umeng.umsdk:common:2.0.0
Failed to resolve: com.umeng.umsdk:share-wx:6.9.4
Failed to resolve: com.umeng.umsdk:share-core:6.9.4
Show in Project Structure dialog
Affected Modules: app

**Comment by codyer** [comment]
> 环境都是最新版，按照集成步骤下来，提示报错
> 友盟sdk导不进来:
> Failed to resolve: com.umeng.umsdk:common:2.0.0
> Failed to resolve: com.umeng.umsdk:share-wx:6.9.4
> Failed to resolve: com.umeng.umsdk:share-core:6.9.4
> Show in Project Structure dialog
> Affected Modules: app

你是集成哪个模块呢？还是只是运行我的工程出的问题？

**Comment by codyer** [comment]
> 环境都是最新版，按照集成步骤下来，提示报错
> 友盟sdk导不进来:
> Failed to resolve: com.umeng.umsdk:common:2.0.0
> Failed to resolve: com.umeng.umsdk:share-wx:6.9.4
> Failed to resolve: com.umeng.umsdk:share-core:6.9.4
> Show in Project Structure dialog
> Affected Modules: app

**Comment by codyer** [comment]
> 环境都是最新版，按照集成步骤下来，提示报错
> 友盟sdk导不进来:
> Failed to resolve: com.umeng.umsdk:common:2.0.0
> Failed to resolve: com.umeng.umsdk:share-wx:6.9.4
> Failed to resolve: com.umeng.umsdk:share-core:6.9.4
> Show in Project Structure dialog
> Affected Modules: app

可以看看 demo-app的集成

**Comment by whiteboolean** [comment]
> > 环境都是最新版，按照集成步骤下来，提示报错
> > 友盟sdk导不进来:
> > Failed to resolve: com.umeng.umsdk:common:2.0.0
> > Failed to resolve: com.umeng.umsdk:share-wx:6.9.4
> > Failed to resolve: com.umeng.umsdk:share-core:6.9.4
> > Show in Project Structure dialog
> > Affected Modules: app
> 
> 可以看看 demo-app的集成

implementation 'com.github.codyer.component:core:1.0.66'
  annotationProcessor 'com.github.codyer.component:compiler:1.0.66'
新建了个项目 然后引入上面两行库之后 sync ，就会提示Failed to reslove xxx

**Comment by codyer** [comment]
> > > 环境都是最新版，按照集成步骤下来，提示报错
> 
> > > 友盟sdk导不进来:
> 
> > > Failed to resolve: com.umeng.umsdk:common:2.0.0
> 
> > > Failed to resolve: com.umeng.umsdk:share-wx:6.9.4
> 
> > > Failed to resolve: com.umeng.umsdk:share-core:6.9.4
> 
> > > Show in Project Structure dialog
> 
> > > Affected Modules: app
> 
> > 
> 
> > 可以看看 demo-app的集成
> 
> 
> 
> implementation 'com.github.codyer.component:core:1.0.66'
> 
>   annotationProcessor 'com.github.codyer.component:compiler:1.0.66'
> 
> 新建了个项目 然后引入上面两行库之后 sync ，就会提示Failed to reslove xxx 

不好意思，莫名其妙issue被关掉了，请问后来找到问题了吗？
