### ISSUE TITLE
Jvm找不到

### ISSUE THREAD

**Issue by WWGsky** [codyer/component#3]
![image](https://user-images.githubusercontent.com/31740148/108450794-b90e7b80-72a0-11eb-8d33-e1b2bdcecc33.png)
![image](https://user-images.githubusercontent.com/31740148/108450854-cd527880-72a0-11eb-8ded-7eaac710c975.png)
更改AS版本和Gradle版本后,直接打开下载好并解压的项目文件夹进行编译,提示找不到 Jvm 
更改之后的 Build.gradle
![image](https://user-images.githubusercontent.com/31740148/108451048-1c98a900-72a1-11eb-83f8-27050e9b1287.png)
更改之后的 gradle-wrapper.properties
![image](https://user-images.githubusercontent.com/31740148/108451111-33d79680-72a1-11eb-8a32-8dcf47106c13.png)
我的JDK版本
![image](https://user-images.githubusercontent.com/31740148/108451166-536ebf00-72a1-11eb-891a-f2ea724f5bda.png)
![image](https://user-images.githubusercontent.com/31740148/108451191-59fd3680-72a1-11eb-9c87-2ff35d761274.png)
我的Java版本
![image](https://user-images.githubusercontent.com/31740148/108451243-700af700-72a1-11eb-9a0d-49d676aa54b4.png)

**Comment by codyer** [comment]
建议使用jdk8

Android系统与Java的版本对应关系
时间 | Android操作系统 | Java | API
-- | -- | -- | --
2013年10月及以前 | 4.4及以前 | 6 | ≤19
2014年10月 | 5.0 | 7 | 21
2015年3月 | 5.1 | 7 | 22
2015年8月 | 6.0 | 7 | 23
2016年8月 | 7.0 | 8 | 24
2018年8月 | 9.0（当前主流） | 8 | 28
2019年9月 | 10.0 | 8 | 29

注意：
>1.android只支持Java8的部分特性如Lambda表达式，方法引用，类型注解，重复注解，默认和静态接口方法。其中只有Lambda>表达式和方法引用可以兼容低版本Android系统。

>2.由于Android Studio新版并未官方支持Java的后续版本，所以Java的9、10、11、12、13版本Android都不支持。

>3.Android11已在开发中，按规律有可能在2020年9月左右发布，目前没有java方面新特性的消息。
