### ISSUE TITLE
疑似错别字一个

### ISSUE THREAD

**Issue by WWGsky** [codyer/component#4]
![image](https://user-images.githubusercontent.com/31740148/108451982-ac8b2280-72a2-11eb-817a-4d3a741d0b36.png)
应该是 大部分 ?

**Comment by codyer** [comment]
> ![image](https://user-images.githubusercontent.com/31740148/108451982-ac8b2280-72a2-11eb-817a-4d3a741d0b36.png)
> 应该是 大部分 ?

已修改，感谢提醒
